# Generated by Django 3.1.5 on 2021-01-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210129_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
