# Generated by Django 3.1.5 on 2021-01-29 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210129_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_choice', models.CharField(choices=[('PC', 'PC'), ('LAPTOP', 'LAPTOP')], default='PC', max_length=1020)),
                ('brand', models.CharField(max_length=254)),
                ('model_name', models.CharField(max_length=254)),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('stock', models.BooleanField()),
                ('reccomended', models.BooleanField()),
                ('description', models.TextField()),
                ('os', models.CharField(max_length=1020)),
                ('cpu', models.CharField(max_length=1020)),
                ('gpu', models.CharField(max_length=1020)),
                ('ram', models.CharField(max_length=1020)),
                ('storage', models.CharField(max_length=1020)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
