# Generated by Django 3.1.5 on 2021-01-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='device_choice',
            new_name='device_type',
        ),
    ]
