# Generated by Django 3.1.5 on 2021-01-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='overall',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='power',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='speed',
        ),
    ]
